name: weatherapp
description: Demo weather app
publish_to: 'none' 


version: 1.0.0+3


environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ox_sdk:
    git: 
      ref: main
      url: https://github.com/Romain-Guillot/ox_sdk.git
    # path: ../../ox_sdk
  flex_color_scheme: ^7.1.2
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.0
  intl: any
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  lottie: ^2.3.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  share_plus: ^6.3.1
  cross_file: ^0.3.3+4
  flutter_timezone: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  freezed: ^2.3.2
  retrofit_generator: ^6.0.0+3
  json_serializable: ^6.6.1
  isar_generator: ^3.1.0+1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

spider:
  generate_tests: true
  no_comments: true
  export: true
  use_part_of: true
  use_references_list: false
  package: resources
  groups:
    - path: assets/images
      class_name: Images
      types: [ .png, .jpg, .svg, .jpeg, .webp, .webm, .bmp , .json]